version: "2.3"


services:
  ble:
    build: .
    volumes:
# device, bluetooth
      - /dev:/dev
      - /sys/devices:/sys/devices
      - /var/lib/bluetooth:/var/lib/bluetooth
      - /run/dbus:/run/dbus
      - /run/udev:/run/udev:ro
      - /var/run/dbus:/var/run/dbus
# for systemctl
      - /run/systemd/system:/run/systemd/system
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - /sys/fs/cgroup:/sys/fs/cgroup
# for systemctl --user
      - /run/user:/run/user
      - ../cabot-device-check:/opt/cabot-device-check
      - /usr/bin/docker:/usr/bin/docker
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
      - /var/run/docker.sock:/var/run/docker.sock
# for ssh in check_device_status.sh
      - ~/.ssh:/home/developer/.ssh
      - ./cabot_ble.py:/root/cabot_ble.py
    environment:
      - CABOT_NAME
      - CABOT_BLE_ADAPTOR
      - CABOT_START_AT_LAUNCH
      - CABOT_ACE_BATTERY_PORT
      - CABOT_ACE_BATTERY_BAUD
      - CABOT_REALSENSE_SERIAL_1
      - CABOT_REALSENSE_SERIAL_2
      - CABOT_REALSENSE_SERIAL_3
      - CABOT_CAMERA_NAME_1
      - CABOT_CAMERA_NAME_2
      - CABOT_CAMERA_NAME_3
      - CABOT_JETSON_CONFIG
      - CABOT_USER_NAME
      - CABOT_ID_DIR=/home/developer/.ssh
      - CABOT_ID_FILE
      - LIDAR_IF
      - LIDAR_IP
      - MICRO_CONTROLLER
      - LANG
# required for display, device, and systemctl
    privileged: true
# device, bluetooth
    devices:
      - /dev/dri
# device, bluetooth
    network_mode: host
    command: ./cabot_ble.py

  simple:
    extends: ble
    volumes:
      - ./simple.py:/root/simple.py
    command: ./simple.py
